import { CosmicNode, CosmicEdge, PeerInfo } from './types';

export const INITIAL_PEERS: PeerInfo[] = [
  {
    id: 'peer-core-hub',
    name: 'Token-Free Gateway Origin Hub',
    region: 'Seoul Edge DC #01',
    protocol: 'Direct WebSocket',
    latencyMs: 3,
    status: 'connected',
    notesCount: 18,
    reputation: 100,
    avatarColor: '#38bdf8',
    joinedAt: '2026-09-04 00:00:00',
  },
  {
    id: 'peer-kr-yeon',
    name: 'Dr. Yeon (Local Vault)',
    region: 'Seoul / WebRTC Peer',
    protocol: 'WebRTC',
    latencyMs: 8,
    status: 'connected',
    notesCount: 7,
    reputation: 99.8,
    avatarColor: '#10b981',
    joinedAt: '2026-09-06 01:14:22',
  },
  {
    id: 'peer-tokyo-shibuya',
    name: 'Shibuya WebGPU Shard #89',
    region: 'Tokyo / WebRTC DC',
    protocol: 'WebRTC',
    latencyMs: 28,
    status: 'connected',
    notesCount: 5,
    reputation: 97.4,
    avatarColor: '#a855f7',
    joinedAt: '2026-09-06 02:40:11',
  },
  {
    id: 'peer-sf-agent',
    name: 'Bay Area Agent Mesh Relay',
    region: 'US-West / libp2p',
    protocol: 'libp2p',
    latencyMs: 142,
    status: 'connected',
    notesCount: 9,
    reputation: 98.6,
    avatarColor: '#f59e0b',
    joinedAt: '2026-09-06 02:55:00',
  },
];

export const INITIAL_NODES: CosmicNode[] = [
  // 1. Core Map of Content (MOC)
  {
    id: 'note-muhanai-core',
    label: '[[MuhanAI Origin MOC.md]]',
    type: 'core',
    x: 0,
    y: 0,
    vx: 0,
    vy: 0,
    radius: 18,
    pinned: true,
    color: '#38bdf8',
    connectionsCount: 8,
    frontmatter: {
      title: 'MuhanAI Origin MOC',
      author: 'Gateway Genesis',
      created: '2026-09-04',
      tags: ['moc', 'core', 'mesh', 'zero-token'],
      links: ['note-webrtc-crdt', 'note-zero-token-routing', 'agent-claude', 'agent-deepseek'],
      summary: 'MuhanAI 분산 P2P 지식 레이크 및 제로 토큰 게이트웨이의 최상위 Map of Content',
      markdown: `# MuhanAI Origin MOC (Map of Content)\n\n분산 P2P 지식 레이크와 개인 MCP 에이전트, 토큰 없는 추론 라우팅을 통합한 지식 그래프의 중심 허브입니다.\n\n## Core Principles\n- **Zero-Token Gateway**: 브라우저와 엣지 노드가 결합하여 API 비용 없이 자율 합의 형성\n- **WebRTC Knowledge Lake**: [[CRDT Knowledge Lake.md]] 기반의 충돌 없는 지식 동기화\n- **Obsidian Graph Integration**: 유저가 개인 옵시디언 볼트를 연결하면 지식 파편이 우주 토폴로지에 실시간 맵핑됨\n\n## Sub-Graphs\n- [[Zero-Token Routing Architecture.md]]\n- [[CRDT Knowledge Lake.md]]\n- [[Personal Vault Sync Protocol.md]]`,
    },
  },
  {
    id: 'note-webrtc-crdt',
    label: '[[CRDT Knowledge Lake.md]]',
    type: 'note',
    peerId: 'peer-kr-yeon',
    x: -140,
    y: -90,
    vx: 0,
    vy: 0,
    radius: 13,
    color: '#10b981',
    connectionsCount: 5,
    frontmatter: {
      title: 'CRDT Knowledge Lake',
      author: 'Dr. Yeon',
      peerId: 'peer-kr-yeon',
      created: '2026-09-06',
      tags: ['crdt', 'webrtc', 'p2p-sync'],
      links: ['note-muhanai-core', 'note-webrtc-mtu', 'tag-crdt'],
      summary: 'State-based CRDT를 활용한 P2P 지식 그래프 실시간 병합 프로토콜',
      markdown: `# CRDT Knowledge Lake\n\n분산 피어 간 지식 노드가 동시에 편집되거나 새로 유입될 때 LWW-Element-Set 및 OR-Set을 결합하여 무결성을 보장합니다.\n\n\`\`\`ts\ninterface CRDTNodePayload {\n  nodeId: string;\n  versionVector: Map<string, number>;\n  obsidianFrontmatter: Record<string, any>;\n  links: string[];\n}\n\`\`\`\n\n- See: [[WebRTC DataChannel MTU.md]]\n- Tag: #crdt #webrtc`,
    },
  },
  {
    id: 'note-webrtc-mtu',
    label: '[[WebRTC DataChannel MTU.md]]',
    type: 'note',
    peerId: 'peer-kr-yeon',
    x: -240,
    y: -150,
    vx: 0,
    vy: 0,
    radius: 11,
    color: '#10b981',
    connectionsCount: 3,
    frontmatter: {
      title: 'WebRTC DataChannel MTU & Fragmentation',
      author: 'Dr. Yeon',
      peerId: 'peer-kr-yeon',
      created: '2026-09-06',
      tags: ['webrtc', 'network', 'mtu'],
      links: ['note-webrtc-crdt'],
      summary: 'SCTP 기반 16KB 청크 분할 및 지연 없는 바이너리 전송 최적화',
      markdown: `# WebRTC DataChannel MTU & Fragmentation\n\n브라우저 간 직접 통신에서 SCTP 청크를 16KB 단위로 슬라이스하여 패킷 유실 시 빠른 재전송을 달성합니다.\n\n- 최대 전송 단위: 16,384 bytes\n- 암호화: DTLS 1.3\n- 연결 프로토콜: [[CRDT Knowledge Lake.md]]`,
    },
  },
  {
    id: 'note-zero-token-routing',
    label: '[[Zero-Token Routing Architecture.md]]',
    type: 'note',
    peerId: 'peer-core-hub',
    x: 160,
    y: -80,
    vx: 0,
    vy: 0,
    radius: 14,
    color: '#38bdf8',
    connectionsCount: 5,
    frontmatter: {
      title: 'Zero-Token Routing Architecture',
      author: 'MuhanAI Gateway',
      peerId: 'peer-core-hub',
      created: '2026-09-05',
      tags: ['zero-token', 'architecture', 'routing'],
      links: ['note-muhanai-core', 'agent-claude', 'agent-deepseek'],
      summary: '로컬 브라우저 세션 및 P2P 리버스 프록시를 통한 무과금 추론 파이프라인',
      markdown: `# Zero-Token Routing Architecture\n\n중앙 결제 게이트웨이 없이 로컬 세션 쿠키 및 P2P WebRTC 중계 터널을 통해 대형 언어 모델의 지능을 공유하는 시스템.\n\n- 로컬 WebGPU 추론: Llama 3.3 8B\n- 고도 추론 위임: Claude 3.7 & DeepSeek R1 Quorum\n- 세션 보호: 로컬 샌드박스 볼트`,
    },
  },
  {
    id: 'agent-claude',
    label: '[[Claude 3.7 Sonnet Peer.md]]',
    type: 'agent',
    x: 120,
    y: 120,
    vx: 0,
    vy: 0,
    radius: 15,
    color: '#e6ff87',
    connectionsCount: 4,
    frontmatter: {
      title: 'Claude 3.7 Sonnet Peer Node',
      author: 'Anthropic Relay Hub',
      created: '2026-09-05',
      tags: ['agent', 'reasoning', 'ast', 'typescript'],
      links: ['note-muhanai-core', 'agent-deepseek', 'note-zero-token-routing'],
      summary: 'TypeScript AST 분석, 아키텍처 검증 및 코드 합성 에이전트',
      markdown: `# Claude 3.7 Sonnet Peer Node\n\n분산 네트워크의 고난도 추론 및 지식 검증을 전담하는 피어 에이전트입니다.\n\n- 작업 성공률: 99.9%\n- 특기: 시스템 구조 설계, AST 리팩터링\n- 연계: [[DeepSeek R1 Quorum.md]], [[MuhanAI Origin MOC.md]]`,
    },
  },
  {
    id: 'agent-deepseek',
    label: '[[DeepSeek R1 Quorum.md]]',
    type: 'agent',
    x: 240,
    y: 160,
    vx: 0,
    vy: 0,
    radius: 14,
    color: '#8b5cf6',
    connectionsCount: 4,
    frontmatter: {
      title: 'DeepSeek R1 Quorum Node',
      author: 'Open Source Logic Mesh',
      created: '2026-09-05',
      tags: ['agent', 'logic', 'math', 'quorum'],
      links: ['agent-claude', 'note-zero-token-routing'],
      summary: '수학적 검증 및 다중 에이전트 합의(Consensus) 정밀 연산 노드',
      markdown: `# DeepSeek R1 Quorum Node\n\n복잡한 논리 증명과 다중 에이전트 합의 정족수를 수학적으로 검증하는 노드입니다.\n\n- 추론 체인: Long-Context Thinking Process\n- 연동: [[Zero-Token Routing Architecture.md]]`,
    },
  },
  {
    id: 'agent-gemini',
    label: '[[Gemini 2.5 Pro Lake.md]]',
    type: 'agent',
    x: -80,
    y: 160,
    vx: 0,
    vy: 0,
    radius: 14,
    color: '#38bdf8',
    connectionsCount: 3,
    frontmatter: {
      title: 'Gemini 2.5 Pro Lake Node',
      author: 'Google Multimodal Mesh',
      created: '2026-09-05',
      tags: ['agent', 'search', 'grounding', 'multimodal'],
      links: ['note-muhanai-core', 'note-vector-search'],
      summary: '실시간 분산 웹 검색 및 그라운딩 검증 에이전트',
      markdown: `# Gemini 2.5 Pro Lake Node\n\n웹 인덱스와 분산 지식 베이스의 사실 여부를 크로스체크하고 그라운딩하는 멀티모달 노드입니다.\n\n- 연계: [[Vector Search & RAG Shard.md]]`,
    },
  },
  {
    id: 'note-vector-search',
    label: '[[Vector Search & RAG Shard.md]]',
    type: 'note',
    peerId: 'peer-tokyo-shibuya',
    x: -190,
    y: 190,
    vx: 0,
    vy: 0,
    radius: 12,
    color: '#a855f7',
    connectionsCount: 4,
    frontmatter: {
      title: 'Vector Search & RAG Shard',
      author: 'Tokyo Shibuya Node',
      peerId: 'peer-tokyo-shibuya',
      created: '2026-09-06',
      tags: ['rag', 'vector', 'embedding'],
      links: ['agent-gemini', 'tag-knowledge'],
      summary: 'pgvector 및 HNSW 인덱스를 활용한 하이브리드 지식 검색 샤드',
      markdown: `# Vector Search & RAG Shard\n\n옵시디언 마크다운의 문맥 임베딩 벡터를 코사인 유사도로 고속 검색하는 분산 인덱스입니다.\n\n- 차원: 1536 dim / BGE-M3 1024 dim\n- 레이턴시: 14ms`,
    },
  },
  {
    id: 'note-personal-vault-sync',
    label: '[[Personal Vault Sync Protocol.md]]',
    type: 'note',
    peerId: 'peer-sf-agent',
    x: 40,
    y: -210,
    vx: 0,
    vy: 0,
    radius: 12,
    color: '#f59e0b',
    connectionsCount: 3,
    frontmatter: {
      title: 'Personal Vault Sync Protocol',
      author: 'SF Mesh Relay',
      peerId: 'peer-sf-agent',
      created: '2026-09-06',
      tags: ['obsidian', 'vault', 'sync'],
      links: ['note-muhanai-core', 'tag-obsidian'],
      summary: '로컬 옵시디언 파일시스템(.obsidian)과 P2P 지식 그래프 간 양방향 실시간 동기화',
      markdown: `# Personal Vault Sync Protocol\n\n유저 피어가 로컬 옵시디언 볼트를 네트워크에 연동하면, 프라이빗 마크다운은 로컬 암호화된 채로 공개 지식 그래프 시냅스만 P2P 네트워크에 안전하게 맵핑됩니다.\n\n- 암호화: AES-GCM 256-bit\n- 태그 동기화: [[MuhanAI Origin MOC.md]]`,
    },
  },
  // Tags
  {
    id: 'tag-obsidian',
    label: '#obsidian',
    type: 'tag',
    x: 120,
    y: -280,
    vx: 0,
    vy: 0,
    radius: 9,
    color: '#f43f5e',
    connectionsCount: 3,
    frontmatter: {
      title: '#obsidian',
      author: 'System',
      created: '2026-09-06',
      tags: ['tag', 'obsidian'],
      links: ['note-personal-vault-sync'],
      summary: '옵시디언 마크다운 지식 그래프 연동 태그',
      markdown: `# Tag: #obsidian\n\n옵시디언 유저 볼트와 마크다운 기반 위키링크 지식 구조를 나타내는 태그입니다.`,
    },
  },
  {
    id: 'tag-crdt',
    label: '#crdt',
    type: 'tag',
    x: -300,
    y: -50,
    vx: 0,
    vy: 0,
    radius: 9,
    color: '#f43f5e',
    connectionsCount: 3,
    frontmatter: {
      title: '#crdt',
      author: 'System',
      created: '2026-09-06',
      tags: ['tag', 'crdt'],
      links: ['note-webrtc-crdt'],
      summary: 'Conflict-Free Replicated Data Types 프로토콜 태그',
      markdown: `# Tag: #crdt\n\n분산 동기화 및 무충돌 상태 병합 알고리즘 태그입니다.`,
    },
  },
  {
    id: 'tag-knowledge',
    label: '#knowledge-mesh',
    type: 'tag',
    x: -220,
    y: 280,
    vx: 0,
    vy: 0,
    radius: 9,
    color: '#f43f5e',
    connectionsCount: 3,
    frontmatter: {
      title: '#knowledge-mesh',
      author: 'System',
      created: '2026-09-06',
      tags: ['tag', 'knowledge'],
      links: ['note-vector-search'],
      summary: '분산 AI 지식 레이크 태그',
      markdown: `# Tag: #knowledge-mesh\n\n집단 지성과 AI 에이전트가 공유하는 지식 메쉬 태그입니다.`,
    },
  },
];

export const INITIAL_EDGES: CosmicEdge[] = [
  { id: 'e1', source: 'note-muhanai-core', target: 'note-webrtc-crdt', label: 'synchronizes', weight: 1.5 },
  { id: 'e2', source: 'note-muhanai-core', target: 'note-zero-token-routing', label: 'routes', weight: 1.8 },
  { id: 'e3', source: 'note-muhanai-core', target: 'agent-claude', label: 'reasons', weight: 1.4 },
  { id: 'e4', source: 'note-muhanai-core', target: 'agent-gemini', label: 'grounds', weight: 1.2 },
  { id: 'e5', source: 'note-muhanai-core', target: 'note-personal-vault-sync', label: 'vault-sync', weight: 1.6 },
  { id: 'e6', source: 'note-webrtc-crdt', target: 'note-webrtc-mtu', label: 'transports', weight: 1.3 },
  { id: 'e7', source: 'note-zero-token-routing', target: 'agent-claude', label: 'delegates', weight: 1.5 },
  { id: 'e8', source: 'note-zero-token-routing', target: 'agent-deepseek', label: 'proves', weight: 1.4 },
  { id: 'e9', source: 'agent-claude', target: 'agent-deepseek', label: 'co-reasons', weight: 1.6 },
  { id: 'e10', source: 'agent-gemini', target: 'note-vector-search', label: 'indexes', weight: 1.3 },
  { id: 'e11', source: 'note-personal-vault-sync', target: 'tag-obsidian', label: 'tagged', weight: 1.0 },
  { id: 'e12', source: 'note-webrtc-crdt', target: 'tag-crdt', label: 'tagged', weight: 1.0 },
  { id: 'e13', source: 'note-vector-search', target: 'tag-knowledge', label: 'tagged', weight: 1.0 },
];
