name = "muhanai"
main = "deploy/worker.ts"
compatibility_date = "2026-09-03"

routes = [
  { pattern = "muhanai.com/*", zone_name = "muhanai.com" },
  { pattern = "www.muhanai.com/*", zone_name = "muhanai.com" },
  { pattern = "find.muhanai.com/*", zone_name = "muhanai.com" },
]
workers_dev = false

[vars]
API_ORIGIN = "https://api.muhanai.com"

[[kv_namespaces]]
binding = "FEED_KV"
id = "d686b4fb62384fb8a13d0e27c3b52947"

[assets]
directory = "apps/web/dist"
binding = "ASSETS"
