#!/usr/bin/env bash
# Continuous Monitoring & Auto-Fix Script for MuhanAI
# Run via cron: 0 */6 * * * /path/to/continuous-monitor.sh >> /var/log/muhanai-monitor.log 2>&1
# Or as systemd timer/service

set -euo pipefail

# ===========================================
# CONFIGURATION
# ===========================================
PROJECT_ROOT="/Users/brianyeon/token-free-gateway.worktrees/muhanai-com-bug-fix-investigation/packaging/npm/token-free-gateway/agentmesh"
LOG_DIR="${PROJECT_ROOT}/.monitor-logs"
MAX_LOG_AGE_DAYS=7
MAX_FIX_ATTEMPTS=3
NOTIFICATION_WEBHOOK="${MUHANAI_MONITOR_WEBHOOK:-}"  # Optional: Slack/Discord webhook

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# ===========================================
# UTILITY FUNCTIONS
# ===========================================
log() {
    local level="$1"
    shift
    local message="$*"
    local timestamp=$(date '+%Y-%m-%d %H:%M:%S')
    echo -e "${timestamp} [${level}] ${message}"
}

log_info() { log "${BLUE}INFO${NC}" "$@"; }
log_warn() { log "${YELLOW}WARN${NC}" "$@"; }
log_error() { log "${RED}ERROR${NC}" "$@"; }
log_success() { log "${GREEN}SUCCESS${NC}" "$@"; }

notify() {
    local title="$1"
    local message="$2"
    local color="${3:-#36a64f}"
    
    if [[ -n "${NOTIFICATION_WEBHOOK}" ]]; then
        curl -s -X POST "${NOTIFICATION_WEBHOOK}" \
            -H "Content-Type: application/json" \
            -d "{\"attachments\":[{\"color\":\"${color}\",\"title\":\"${title}\",\"text\":\"${message}\",\"ts\":$(date +%s)}]}" \
            > /dev/null || true
    fi
}

cleanup_old_logs() {
    find "${LOG_DIR}" -name "*.log" -mtime +${MAX_LOG_AGE_DAYS} -delete 2>/dev/null || true
}

run_check() {
    local name="$1"
    local cmd="$2"
    local log_file="${LOG_DIR}/${name}-$(date +%Y%m%d-%H%M%S).log"
    
    log_info "Running ${name}..."
    if eval "${cmd}" > "${log_file}" 2>&1; then
        log_success "${name} passed"
        echo "PASS"
        return 0
    else
        log_error "${name} failed (see ${log_file})"
        echo "FAIL"
        return 1
    fi
}

attempt_fix() {
    local attempt="$1"
    log_info "Attempting auto-fix (attempt ${attempt}/${MAX_FIX_ATTEMPTS})..."
    
    cd "${PROJECT_ROOT}"
    
    # 1. Biome auto-fix
    log_info "Running biome check --write..."
    if pnpm exec biome check --write . > "${LOG_DIR}/biome-fix-${attempt}.log" 2>&1; then
        log_success "Biome auto-fix completed"
    else
        log_warn "Biome auto-fix had issues"
    fi
    
    # 2. Check if files changed
    if git diff --quiet; then
        log_warn "No files changed by auto-fix"
        return 1
    fi
    
    log_info "Files modified by auto-fix:"
    git diff --stat
    
    # 3. Verify TypeScript
    log_info "Verifying TypeScript..."
    if pnpm typecheck > "${LOG_DIR}/typecheck-verify-${attempt}.log" 2>&1; then
        log_success "TypeScript verification passed"
    else
        log_error "TypeScript verification failed"
        cat "${LOG_DIR}/typecheck-verify-${attempt}.log"
        return 1
    fi
    
    # 4. Run tests
    log_info "Running tests..."
    if pnpm test > "${LOG_DIR}/test-verify-${attempt}.log" 2>&1; then
        log_success "Tests passed"
        return 0
    else
        log_error "Tests failed after fix"
        cat "${LOG_DIR}/test-verify-${attempt}.log"
        return 1
    fi
}

create_pr() {
    local branch="autofix/local-$(date +%Y%m%d-%H%M%S)"
    log_info "Creating PR branch: ${branch}"
    
    cd "${PROJECT_ROOT}"
    git checkout -b "${branch}"
    git add -A
    git commit -m "[Auto-Fix] Local monitoring fixes $(date '+%Y-%m-%d %H:%M:%S')"
    git push origin "${branch}"
    
    # Create PR via gh CLI if available
    if command -v gh >/dev/null 2>&1; then
        gh pr create \
            --title "[Auto-Fix] Local monitoring fixes" \
            --body "Automated fixes from local continuous monitoring script.

**Changes:**
$(git diff --stat origin/main)

**Verification:**
- TypeCheck: ✅
- Tests: ✅

*Generated by continuous-monitor.sh*" \
            --label "auto-fix,local-monitoring" \
            --assignee "@me"
    else
        log_warn "gh CLI not available, pushed branch ${branch} - create PR manually"
    fi
}

check_production_health() {
    log_info "Checking production endpoints..."
    local failed=0
    
    for endpoint in "https://api.muhanai.com/health" "https://vn.kbizhub.com/health" "https://muhanai.com"; do
        if curl -sf --max-time 10 "${endpoint}" > /dev/null; then
            log_success "${endpoint} healthy"
        else
            log_error "${endpoint} DOWN"
            ((failed++))
        fi
    done
    
    return ${failed}
}

# ===========================================
# MAIN EXECUTION
# ===========================================
main() {
    local start_time=$(date +%s)
    local run_id="monitor-$(date +%Y%m%d-%H%M%S)"
    
    mkdir -p "${LOG_DIR}"
    cleanup_old_logs
    
    log_info "=== MuhanAI Continuous Monitoring Started (${run_id}) ==="
    notify "MuhanAI Monitoring Started" "Run ID: ${run_id}" "#36a64f"
    
    cd "${PROJECT_ROOT}"
    
    # Track overall status
    local has_errors=0
    local error_details=()
    
    # 1. TypeCheck
    if ! run_check "typecheck" "pnpm typecheck"; then
        has_errors=1
        error_details+=("TypeCheck failed")
    fi
    
    # 2. Lint
    if ! run_check "lint" "pnpm lint"; then
        has_errors=1
        error_details+=("Lint failed")
    fi
    
    # 3. Tests
    if ! run_check "test" "pnpm test"; then
        has_errors=1
        error_details+=("Tests failed")
    fi
    
    # 4. Build (optional, non-blocking)
    run_check "build-web" "cd apps/web && pnpm run build" || log_warn "Web build failed"
    run_check "build-api" "cd services/api && pnpm run build" || log_warn "API build failed"
    
    # 5. Production health check
    if ! check_production_health; then
        has_errors=1
        error_details+=("Production health check failed")
    fi
    
    # ===========================================
    # AUTO-FIX LOOP
    # ===========================================
    if [[ ${has_errors} -eq 1 ]]; then
        log_warn "Errors detected, attempting auto-fix..."
        notify "MuhanAI Monitoring - Errors Detected" "Errors: ${error_details[*]}\nAttempting auto-fix..." "#ff9900"
        
        for attempt in $(seq 1 ${MAX_FIX_ATTEMPTS}); do
            if attempt_fix "${attempt}"; then
                log_success "Auto-fix successful on attempt ${attempt}"
                notify "MuhanAI Monitoring - Auto-Fix Success" "Fixed on attempt ${attempt}/${MAX_FIX_ATTEMPTS}" "#36a64f"
                
                # Create PR
                create_pr
                has_errors=0
                break
            else
                log_warn "Auto-fix attempt ${attempt} failed"
                if [[ ${attempt} -eq ${MAX_FIX_ATTEMPTS} ]]; then
                    notify "MuhanAI Monitoring - Auto-Fix Failed" "All ${MAX_FIX_ATTEMPTS} attempts failed. Manual intervention needed.\nErrors: ${error_details[*]}" "#ff0000"
                fi
            fi
        done
    else
        log_success "All checks passed!"
        notify "MuhanAI Monitoring - All Checks Passed" "Run ID: ${run_id}" "#36a64f"
    fi
    
    local end_time=$(date +%s)
    local duration=$((end_time - start_time))
    log_info "=== Monitoring completed in ${duration}s ==="
    
    # Exit with error code if issues remain
    exit ${has_errors}
}

# ===========================================
# ENTRY POINT
# ===========================================
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi